version: "3.8"
services:
  db:
    image: postgres:16
    container_name: nightshift-db
    environment:
      POSTGRES_DB: nightshift
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - "5433:5433"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nightshift-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/nightshift
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: toor
    ports:
      - "8080:8080"

volumes:
  db-data:
